// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proplyd/v1/cache.proto

package proplydpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadStrategy int32

const (
	ReadStrategy_READ_STRATEGY_UNSPECIFIED ReadStrategy = 0 // defaults to READ_THROUGH
	// Client loads from the store on a miss and calls Fill.
	ReadStrategy_READ_STRATEGY_CACHE_ASIDE ReadStrategy = 1
	// Cache loads from the store on a miss (deduplicated per key).
	ReadStrategy_READ_STRATEGY_READ_THROUGH ReadStrategy = 2
	// Read-through, plus entries older than refresh_after are reloaded in the
	// background while the cached value keeps being served.
	ReadStrategy_READ_STRATEGY_REFRESH_AHEAD ReadStrategy = 3
)

// Enum value maps for ReadStrategy.
var (
	ReadStrategy_name = map[int32]string{
		0: "READ_STRATEGY_UNSPECIFIED",
		1: "READ_STRATEGY_CACHE_ASIDE",
		2: "READ_STRATEGY_READ_THROUGH",
		3: "READ_STRATEGY_REFRESH_AHEAD",
	}
	ReadStrategy_value = map[string]int32{
		"READ_STRATEGY_UNSPECIFIED":   0,
		"READ_STRATEGY_CACHE_ASIDE":   1,
		"READ_STRATEGY_READ_THROUGH":  2,
		"READ_STRATEGY_REFRESH_AHEAD": 3,
	}
)

func (x ReadStrategy) Enum() *ReadStrategy {
	p := new(ReadStrategy)
	*p = x
	return p
}

func (x ReadStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proplyd_v1_cache_proto_enumTypes[0].Descriptor()
}

func (ReadStrategy) Type() protoreflect.EnumType {
	return &file_proplyd_v1_cache_proto_enumTypes[0]
}

func (x ReadStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadStrategy.Descriptor instead.
func (ReadStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{0}
}

type WriteStrategy int32

const (
	WriteStrategy_WRITE_STRATEGY_UNSPECIFIED WriteStrategy = 0 // defaults to WRITE_THROUGH
	// Cache writes to the store, then updates itself. The write fails if the
	// cache is unreachable: the cache never diverges from the store, but a
	// write can be rejected.
	WriteStrategy_WRITE_STRATEGY_WRITE_THROUGH WriteStrategy = 1
	// Cache writes to the store and invalidates its entry. If the cache is
	// unreachable the client writes to the store directly: every write is
	// recorded, but the cache can briefly serve older data (see sync_mode).
	WriteStrategy_WRITE_STRATEGY_WRITE_AROUND WriteStrategy = 2
	// Cache acknowledges immediately and flushes to the store asynchronously in
	// batches. Writes not yet flushed are LOST if the cache process dies.
	WriteStrategy_WRITE_STRATEGY_WRITE_BEHIND WriteStrategy = 3
)

// Enum value maps for WriteStrategy.
var (
	WriteStrategy_name = map[int32]string{
		0: "WRITE_STRATEGY_UNSPECIFIED",
		1: "WRITE_STRATEGY_WRITE_THROUGH",
		2: "WRITE_STRATEGY_WRITE_AROUND",
		3: "WRITE_STRATEGY_WRITE_BEHIND",
	}
	WriteStrategy_value = map[string]int32{
		"WRITE_STRATEGY_UNSPECIFIED":   0,
		"WRITE_STRATEGY_WRITE_THROUGH": 1,
		"WRITE_STRATEGY_WRITE_AROUND":  2,
		"WRITE_STRATEGY_WRITE_BEHIND":  3,
	}
)

func (x WriteStrategy) Enum() *WriteStrategy {
	p := new(WriteStrategy)
	*p = x
	return p
}

func (x WriteStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proplyd_v1_cache_proto_enumTypes[1].Descriptor()
}

func (WriteStrategy) Type() protoreflect.EnumType {
	return &file_proplyd_v1_cache_proto_enumTypes[1]
}

func (x WriteStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteStrategy.Descriptor instead.
func (WriteStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{1}
}

type EvictionPolicy int32

const (
	EvictionPolicy_EVICTION_POLICY_UNSPECIFIED EvictionPolicy = 0 // defaults to SIEVE
	EvictionPolicy_EVICTION_POLICY_LRU         EvictionPolicy = 1
	EvictionPolicy_EVICTION_POLICY_LFU         EvictionPolicy = 2
	// TINY_LFU and W_TINY_LFU are strongly admission-filtered in samber/hot
	// v0.13 and keep far fewer entries than their capacity.
	EvictionPolicy_EVICTION_POLICY_TINY_LFU   EvictionPolicy = 3
	EvictionPolicy_EVICTION_POLICY_W_TINY_LFU EvictionPolicy = 4
	EvictionPolicy_EVICTION_POLICY_TWO_QUEUE  EvictionPolicy = 5
	// Rejected at registration: samber/hot v0.13 ARC does not bound memory.
	EvictionPolicy_EVICTION_POLICY_ARC   EvictionPolicy = 6
	EvictionPolicy_EVICTION_POLICY_FIFO  EvictionPolicy = 7
	EvictionPolicy_EVICTION_POLICY_SIEVE EvictionPolicy = 8
)

// Enum value maps for EvictionPolicy.
var (
	EvictionPolicy_name = map[int32]string{
		0: "EVICTION_POLICY_UNSPECIFIED",
		1: "EVICTION_POLICY_LRU",
		2: "EVICTION_POLICY_LFU",
		3: "EVICTION_POLICY_TINY_LFU",
		4: "EVICTION_POLICY_W_TINY_LFU",
		5: "EVICTION_POLICY_TWO_QUEUE",
		6: "EVICTION_POLICY_ARC",
		7: "EVICTION_POLICY_FIFO",
		8: "EVICTION_POLICY_SIEVE",
	}
	EvictionPolicy_value = map[string]int32{
		"EVICTION_POLICY_UNSPECIFIED": 0,
		"EVICTION_POLICY_LRU":         1,
		"EVICTION_POLICY_LFU":         2,
		"EVICTION_POLICY_TINY_LFU":    3,
		"EVICTION_POLICY_W_TINY_LFU":  4,
		"EVICTION_POLICY_TWO_QUEUE":   5,
		"EVICTION_POLICY_ARC":         6,
		"EVICTION_POLICY_FIFO":        7,
		"EVICTION_POLICY_SIEVE":       8,
	}
)

func (x EvictionPolicy) Enum() *EvictionPolicy {
	p := new(EvictionPolicy)
	*p = x
	return p
}

func (x EvictionPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvictionPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_proplyd_v1_cache_proto_enumTypes[2].Descriptor()
}

func (EvictionPolicy) Type() protoreflect.EnumType {
	return &file_proplyd_v1_cache_proto_enumTypes[2]
}

func (x EvictionPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvictionPolicy.Descriptor instead.
func (EvictionPolicy) EnumDescriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{2}
}

// SyncMode controls whether the cache watches the backing store for changes
// it did not make itself (direct client writes during an outage, other
// writers) and updates its entries accordingly.
type SyncMode int32

const (
	// WATCH for WRITE_AROUND namespaces, NONE otherwise.
	SyncMode_SYNC_MODE_UNSPECIFIED SyncMode = 0
	SyncMode_SYNC_MODE_WATCH       SyncMode = 1
	// Staleness caused by out-of-band writes is bounded by the TTL only.
	SyncMode_SYNC_MODE_NONE SyncMode = 2
)

// Enum value maps for SyncMode.
var (
	SyncMode_name = map[int32]string{
		0: "SYNC_MODE_UNSPECIFIED",
		1: "SYNC_MODE_WATCH",
		2: "SYNC_MODE_NONE",
	}
	SyncMode_value = map[string]int32{
		"SYNC_MODE_UNSPECIFIED": 0,
		"SYNC_MODE_WATCH":       1,
		"SYNC_MODE_NONE":        2,
	}
)

func (x SyncMode) Enum() *SyncMode {
	p := new(SyncMode)
	*p = x
	return p
}

func (x SyncMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proplyd_v1_cache_proto_enumTypes[3].Descriptor()
}

func (SyncMode) Type() protoreflect.EnumType {
	return &file_proplyd_v1_cache_proto_enumTypes[3]
}

func (x SyncMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncMode.Descriptor instead.
func (SyncMode) EnumDescriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{3}
}

type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	// Answered from memory.
	Outcome_OUTCOME_HIT Outcome = 1
	// Not cached; loaded from the backing store by the cache.
	Outcome_OUTCOME_LOADED Outcome = 2
	// Not cached and not loaded (CACHE_ASIDE): the client must load it.
	Outcome_OUTCOME_MISS Outcome = 3
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_HIT",
		2: "OUTCOME_LOADED",
		3: "OUTCOME_MISS",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_HIT":         1,
		"OUTCOME_LOADED":      2,
		"OUTCOME_MISS":        3,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_proplyd_v1_cache_proto_enumTypes[4].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_proplyd_v1_cache_proto_enumTypes[4]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{4}
}

type WriteBehindConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How often dirty entries are flushed. Default 100ms.
	FlushInterval *durationpb.Duration `protobuf:"bytes,1,opt,name=flush_interval,json=flushInterval,proto3" json:"flush_interval,omitempty"`
	// Maximum number of keys per store transaction. Default 128.
	MaxBatch int32 `protobuf:"varint,2,opt,name=max_batch,json=maxBatch,proto3" json:"max_batch,omitempty"`
	// Maximum number of unflushed keys; further writes fail with
	// RESOURCE_EXHAUSTED until the flusher catches up. Default 100000.
	MaxPending    int64 `protobuf:"varint,3,opt,name=max_pending,json=maxPending,proto3" json:"max_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBehindConfig) Reset() {
	*x = WriteBehindConfig{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBehindConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBehindConfig) ProtoMessage() {}

func (x *WriteBehindConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBehindConfig.ProtoReflect.Descriptor instead.
func (*WriteBehindConfig) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *WriteBehindConfig) GetFlushInterval() *durationpb.Duration {
	if x != nil {
		return x.FlushInterval
	}
	return nil
}

func (x *WriteBehindConfig) GetMaxBatch() int32 {
	if x != nil {
		return x.MaxBatch
	}
	return 0
}

func (x *WriteBehindConfig) GetMaxPending() int64 {
	if x != nil {
		return x.MaxPending
	}
	return 0
}

type NamespaceConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReadStrategy   ReadStrategy           `protobuf:"varint,1,opt,name=read_strategy,json=readStrategy,proto3,enum=proplyd.v1.ReadStrategy" json:"read_strategy,omitempty"`
	WriteStrategy  WriteStrategy          `protobuf:"varint,2,opt,name=write_strategy,json=writeStrategy,proto3,enum=proplyd.v1.WriteStrategy" json:"write_strategy,omitempty"`
	EvictionPolicy EvictionPolicy         `protobuf:"varint,3,opt,name=eviction_policy,json=evictionPolicy,proto3,enum=proplyd.v1.EvictionPolicy" json:"eviction_policy,omitempty"`
	// Maximum number of cached keys. Default 10000.
	Capacity int64 `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Default entry TTL. Zero means entries only leave through eviction.
	Ttl *durationpb.Duration `protobuf:"bytes,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Prefix under which the namespace keys live in the backing store,
	// e.g. "/magnetar/nodes/". Required.
	KeyPrefix string `protobuf:"bytes,6,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	// REFRESH_AHEAD only: entries older than this are refreshed in the
	// background. Default 75% of ttl.
	RefreshAfter *durationpb.Duration `protobuf:"bytes,7,opt,name=refresh_after,json=refreshAfter,proto3" json:"refresh_after,omitempty"`
	WriteBehind  *WriteBehindConfig   `protobuf:"bytes,8,opt,name=write_behind,json=writeBehind,proto3" json:"write_behind,omitempty"`
	SyncMode     SyncMode             `protobuf:"varint,9,opt,name=sync_mode,json=syncMode,proto3,enum=proplyd.v1.SyncMode" json:"sync_mode,omitempty"`
	// Cache "key does not exist" answers (negative caching).
	CacheMisses bool `protobuf:"varint,10,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	// Maximum accepted value size in bytes. Default 1 MiB.
	MaxValueBytes int64 `protobuf:"varint,11,opt,name=max_value_bytes,json=maxValueBytes,proto3" json:"max_value_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceConfig) Reset() {
	*x = NamespaceConfig{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceConfig) ProtoMessage() {}

func (x *NamespaceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceConfig.ProtoReflect.Descriptor instead.
func (*NamespaceConfig) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{1}
}

func (x *NamespaceConfig) GetReadStrategy() ReadStrategy {
	if x != nil {
		return x.ReadStrategy
	}
	return ReadStrategy_READ_STRATEGY_UNSPECIFIED
}

func (x *NamespaceConfig) GetWriteStrategy() WriteStrategy {
	if x != nil {
		return x.WriteStrategy
	}
	return WriteStrategy_WRITE_STRATEGY_UNSPECIFIED
}

func (x *NamespaceConfig) GetEvictionPolicy() EvictionPolicy {
	if x != nil {
		return x.EvictionPolicy
	}
	return EvictionPolicy_EVICTION_POLICY_UNSPECIFIED
}

func (x *NamespaceConfig) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *NamespaceConfig) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *NamespaceConfig) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *NamespaceConfig) GetRefreshAfter() *durationpb.Duration {
	if x != nil {
		return x.RefreshAfter
	}
	return nil
}

func (x *NamespaceConfig) GetWriteBehind() *WriteBehindConfig {
	if x != nil {
		return x.WriteBehind
	}
	return nil
}

func (x *NamespaceConfig) GetSyncMode() SyncMode {
	if x != nil {
		return x.SyncMode
	}
	return SyncMode_SYNC_MODE_UNSPECIFIED
}

func (x *NamespaceConfig) GetCacheMisses() bool {
	if x != nil {
		return x.CacheMisses
	}
	return false
}

func (x *NamespaceConfig) GetMaxValueBytes() int64 {
	if x != nil {
		return x.MaxValueBytes
	}
	return 0
}

type RegisterNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Config        *NamespaceConfig       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNamespaceRequest) Reset() {
	*x = RegisterNamespaceRequest{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNamespaceRequest) ProtoMessage() {}

func (x *RegisterNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNamespaceRequest.ProtoReflect.Descriptor instead.
func (*RegisterNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterNamespaceRequest) GetConfig() *NamespaceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RegisterNamespaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effective configuration with defaults applied.
	Config *NamespaceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Identifies the cache process; changes when the cache restarts.
	Epoch string `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// True if the namespace was created by this call.
	Created       bool `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNamespaceResponse) Reset() {
	*x = RegisterNamespaceResponse{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNamespaceResponse) ProtoMessage() {}

func (x *RegisterNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNamespaceResponse.ProtoReflect.Descriptor instead.
func (*RegisterNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNamespaceResponse) GetConfig() *NamespaceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterNamespaceResponse) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *RegisterNamespaceResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Outcome Outcome                `protobuf:"varint,1,opt,name=outcome,proto3,enum=proplyd.v1.Outcome" json:"outcome,omitempty"`
	// Whether the key exists. Meaningless when outcome is MISS.
	Found bool   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Store revision that last modified the key. 0 for write-behind values
	// that have not been flushed yet.
	ModRevision   int64 `protobuf:"varint,4,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetModRevision() int64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

type SetRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Overrides the namespace TTL for this key.
	Ttl           *durationpb.Duration `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{6}
}

func (x *SetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type SetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Store revision of the write. 0 for write-behind.
	Revision      int64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{7}
}

func (x *SetResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type FillRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Found     bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Value     []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// Revision that last modified the key (0 if not found).
	ModRevision int64 `protobuf:"varint,5,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	// Store revision at which the read was served.
	ReadRevision  int64                `protobuf:"varint,6,opt,name=read_revision,json=readRevision,proto3" json:"read_revision,omitempty"`
	Ttl           *durationpb.Duration `protobuf:"bytes,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillRequest) Reset() {
	*x = FillRequest{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillRequest) ProtoMessage() {}

func (x *FillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillRequest.ProtoReflect.Descriptor instead.
func (*FillRequest) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{10}
}

func (x *FillRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FillRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FillRequest) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FillRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FillRequest) GetModRevision() int64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

func (x *FillRequest) GetReadRevision() int64 {
	if x != nil {
		return x.ReadRevision
	}
	return 0
}

func (x *FillRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type FillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillResponse) Reset() {
	*x = FillResponse{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillResponse) ProtoMessage() {}

func (x *FillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillResponse.ProtoReflect.Descriptor instead.
func (*FillResponse) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{11}
}

func (x *FillResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type InvalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{12}
}

func (x *InvalidateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InvalidateRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type InvalidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateResponse) Reset() {
	*x = InvalidateResponse{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateResponse) ProtoMessage() {}

func (x *InvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateResponse.ProtoReflect.Descriptor instead.
func (*InvalidateResponse) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{13}
}

type PurgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeRequest) Reset() {
	*x = PurgeRequest{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeRequest) ProtoMessage() {}

func (x *PurgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeRequest.ProtoReflect.Descriptor instead.
func (*PurgeRequest) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{14}
}

func (x *PurgeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type PurgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeResponse) Reset() {
	*x = PurgeResponse{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeResponse) ProtoMessage() {}

func (x *PurgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeResponse.ProtoReflect.Descriptor instead.
func (*PurgeResponse) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{15}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{16}
}

func (x *StatsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       int64                  `protobuf:"varint,1,opt,name=entries,proto3" json:"entries,omitempty"`
	Hits          uint64                 `protobuf:"varint,2,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses        uint64                 `protobuf:"varint,3,opt,name=misses,proto3" json:"misses,omitempty"`
	Loads         uint64                 `protobuf:"varint,4,opt,name=loads,proto3" json:"loads,omitempty"`
	LoadErrors    uint64                 `protobuf:"varint,5,opt,name=load_errors,json=loadErrors,proto3" json:"load_errors,omitempty"`
	FillsAccepted uint64                 `protobuf:"varint,6,opt,name=fills_accepted,json=fillsAccepted,proto3" json:"fills_accepted,omitempty"`
	FillsRejected uint64                 `protobuf:"varint,7,opt,name=fills_rejected,json=fillsRejected,proto3" json:"fills_rejected,omitempty"`
	PendingWrites int64                  `protobuf:"varint,8,opt,name=pending_writes,json=pendingWrites,proto3" json:"pending_writes,omitempty"`
	FlushedWrites uint64                 `protobuf:"varint,9,opt,name=flushed_writes,json=flushedWrites,proto3" json:"flushed_writes,omitempty"`
	FlushErrors   uint64                 `protobuf:"varint,10,opt,name=flush_errors,json=flushErrors,proto3" json:"flush_errors,omitempty"`
	WatchEvents   uint64                 `protobuf:"varint,11,opt,name=watch_events,json=watchEvents,proto3" json:"watch_events,omitempty"`
	WatchResyncs  uint64                 `protobuf:"varint,12,opt,name=watch_resyncs,json=watchResyncs,proto3" json:"watch_resyncs,omitempty"`
	Refreshes     uint64                 `protobuf:"varint,13,opt,name=refreshes,proto3" json:"refreshes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proplyd_v1_cache_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proplyd_v1_cache_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proplyd_v1_cache_proto_rawDescGZIP(), []int{17}
}

func (x *StatsResponse) GetEntries() int64 {
	if x != nil {
		return x.Entries
	}
	return 0
}

func (x *StatsResponse) GetHits() uint64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *StatsResponse) GetMisses() uint64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *StatsResponse) GetLoads() uint64 {
	if x != nil {
		return x.Loads
	}
	return 0
}

func (x *StatsResponse) GetLoadErrors() uint64 {
	if x != nil {
		return x.LoadErrors
	}
	return 0
}

func (x *StatsResponse) GetFillsAccepted() uint64 {
	if x != nil {
		return x.FillsAccepted
	}
	return 0
}

func (x *StatsResponse) GetFillsRejected() uint64 {
	if x != nil {
		return x.FillsRejected
	}
	return 0
}

func (x *StatsResponse) GetPendingWrites() int64 {
	if x != nil {
		return x.PendingWrites
	}
	return 0
}

func (x *StatsResponse) GetFlushedWrites() uint64 {
	if x != nil {
		return x.FlushedWrites
	}
	return 0
}

func (x *StatsResponse) GetFlushErrors() uint64 {
	if x != nil {
		return x.FlushErrors
	}
	return 0
}

func (x *StatsResponse) GetWatchEvents() uint64 {
	if x != nil {
		return x.WatchEvents
	}
	return 0
}

func (x *StatsResponse) GetWatchResyncs() uint64 {
	if x != nil {
		return x.WatchResyncs
	}
	return 0
}

func (x *StatsResponse) GetRefreshes() uint64 {
	if x != nil {
		return x.Refreshes
	}
	return 0
}

var File_proplyd_v1_cache_proto protoreflect.FileDescriptor

const file_proplyd_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x16proplyd/v1/cache.proto\x12\n" +
	"proplyd.v1\x1a\x1egoogle/protobuf/duration.proto\"\x93\x01\n" +
	"\x11WriteBehindConfig\x12@\n" +
	"\x0eflush_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\rflushInterval\x12\x1b\n" +
	"\tmax_batch\x18\x02 \x01(\x05R\bmaxBatch\x12\x1f\n" +
	"\vmax_pending\x18\x03 \x01(\x03R\n" +
	"maxPending\"\xbf\x04\n" +
	"\x0fNamespaceConfig\x12=\n" +
	"\rread_strategy\x18\x01 \x01(\x0e2\x18.proplyd.v1.ReadStrategyR\freadStrategy\x12@\n" +
	"\x0ewrite_strategy\x18\x02 \x01(\x0e2\x19.proplyd.v1.WriteStrategyR\rwriteStrategy\x12C\n" +
	"\x0feviction_policy\x18\x03 \x01(\x0e2\x1a.proplyd.v1.EvictionPolicyR\x0eevictionPolicy\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x03R\bcapacity\x12+\n" +
	"\x03ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x06 \x01(\tR\tkeyPrefix\x12>\n" +
	"\rrefresh_after\x18\a \x01(\v2\x19.google.protobuf.DurationR\frefreshAfter\x12@\n" +
	"\fwrite_behind\x18\b \x01(\v2\x1d.proplyd.v1.WriteBehindConfigR\vwriteBehind\x121\n" +
	"\tsync_mode\x18\t \x01(\x0e2\x14.proplyd.v1.SyncModeR\bsyncMode\x12!\n" +
	"\fcache_misses\x18\n" +
	" \x01(\bR\vcacheMisses\x12&\n" +
	"\x0fmax_value_bytes\x18\v \x01(\x03R\rmaxValueBytes\"m\n" +
	"\x18RegisterNamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x123\n" +
	"\x06config\x18\x02 \x01(\v2\x1b.proplyd.v1.NamespaceConfigR\x06config\"\x80\x01\n" +
	"\x19RegisterNamespaceResponse\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x1b.proplyd.v1.NamespaceConfigR\x06config\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\tR\x05epoch\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\"<\n" +
	"\n" +
	"GetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x8b\x01\n" +
	"\vGetResponse\x12-\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x13.proplyd.v1.OutcomeR\aoutcome\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12!\n" +
	"\fmod_revision\x18\x04 \x01(\x03R\vmodRevision\"\x7f\n" +
	"\n" +
	"SetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12+\n" +
	"\x03ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\")\n" +
	"\vSetResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\"?\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\",\n" +
	"\x0eDeleteResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\"\xde\x01\n" +
	"\vFillRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12!\n" +
	"\fmod_revision\x18\x05 \x01(\x03R\vmodRevision\x12#\n" +
	"\rread_revision\x18\x06 \x01(\x03R\freadRevision\x12+\n" +
	"\x03ttl\x18\a \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"*\n" +
	"\fFillResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"E\n" +
	"\x11InvalidateRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"\x14\n" +
	"\x12InvalidateResponse\",\n" +
	"\fPurgeRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\x0f\n" +
	"\rPurgeResponse\",\n" +
	"\fStatsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\xb1\x03\n" +
	"\rStatsResponse\x12\x18\n" +
	"\aentries\x18\x01 \x01(\x03R\aentries\x12\x12\n" +
	"\x04hits\x18\x02 \x01(\x04R\x04hits\x12\x16\n" +
	"\x06misses\x18\x03 \x01(\x04R\x06misses\x12\x14\n" +
	"\x05loads\x18\x04 \x01(\x04R\x05loads\x12\x1f\n" +
	"\vload_errors\x18\x05 \x01(\x04R\n" +
	"loadErrors\x12%\n" +
	"\x0efills_accepted\x18\x06 \x01(\x04R\rfillsAccepted\x12%\n" +
	"\x0efills_rejected\x18\a \x01(\x04R\rfillsRejected\x12%\n" +
	"\x0epending_writes\x18\b \x01(\x03R\rpendingWrites\x12%\n" +
	"\x0eflushed_writes\x18\t \x01(\x04R\rflushedWrites\x12!\n" +
	"\fflush_errors\x18\n" +
	" \x01(\x04R\vflushErrors\x12!\n" +
	"\fwatch_events\x18\v \x01(\x04R\vwatchEvents\x12#\n" +
	"\rwatch_resyncs\x18\f \x01(\x04R\fwatchResyncs\x12\x1c\n" +
	"\trefreshes\x18\r \x01(\x04R\trefreshes*\x8d\x01\n" +
	"\fReadStrategy\x12\x1d\n" +
	"\x19READ_STRATEGY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19READ_STRATEGY_CACHE_ASIDE\x10\x01\x12\x1e\n" +
	"\x1aREAD_STRATEGY_READ_THROUGH\x10\x02\x12\x1f\n" +
	"\x1bREAD_STRATEGY_REFRESH_AHEAD\x10\x03*\x93\x01\n" +
	"\rWriteStrategy\x12\x1e\n" +
	"\x1aWRITE_STRATEGY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cWRITE_STRATEGY_WRITE_THROUGH\x10\x01\x12\x1f\n" +
	"\x1bWRITE_STRATEGY_WRITE_AROUND\x10\x02\x12\x1f\n" +
	"\x1bWRITE_STRATEGY_WRITE_BEHIND\x10\x03*\x8e\x02\n" +
	"\x0eEvictionPolicy\x12\x1f\n" +
	"\x1bEVICTION_POLICY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EVICTION_POLICY_LRU\x10\x01\x12\x17\n" +
	"\x13EVICTION_POLICY_LFU\x10\x02\x12\x1c\n" +
	"\x18EVICTION_POLICY_TINY_LFU\x10\x03\x12\x1e\n" +
	"\x1aEVICTION_POLICY_W_TINY_LFU\x10\x04\x12\x1d\n" +
	"\x19EVICTION_POLICY_TWO_QUEUE\x10\x05\x12\x17\n" +
	"\x13EVICTION_POLICY_ARC\x10\x06\x12\x18\n" +
	"\x14EVICTION_POLICY_FIFO\x10\a\x12\x19\n" +
	"\x15EVICTION_POLICY_SIEVE\x10\b*N\n" +
	"\bSyncMode\x12\x19\n" +
	"\x15SYNC_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSYNC_MODE_WATCH\x10\x01\x12\x12\n" +
	"\x0eSYNC_MODE_NONE\x10\x02*Y\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOUTCOME_HIT\x10\x01\x12\x12\n" +
	"\x0eOUTCOME_LOADED\x10\x02\x12\x10\n" +
	"\fOUTCOME_MISS\x10\x032\xa5\x04\n" +
	"\fCacheService\x12`\n" +
	"\x11RegisterNamespace\x12$.proplyd.v1.RegisterNamespaceRequest\x1a%.proplyd.v1.RegisterNamespaceResponse\x126\n" +
	"\x03Get\x12\x16.proplyd.v1.GetRequest\x1a\x17.proplyd.v1.GetResponse\x126\n" +
	"\x03Set\x12\x16.proplyd.v1.SetRequest\x1a\x17.proplyd.v1.SetResponse\x12?\n" +
	"\x06Delete\x12\x19.proplyd.v1.DeleteRequest\x1a\x1a.proplyd.v1.DeleteResponse\x129\n" +
	"\x04Fill\x12\x17.proplyd.v1.FillRequest\x1a\x18.proplyd.v1.FillResponse\x12K\n" +
	"\n" +
	"Invalidate\x12\x1d.proplyd.v1.InvalidateRequest\x1a\x1e.proplyd.v1.InvalidateResponse\x12<\n" +
	"\x05Purge\x12\x18.proplyd.v1.PurgeRequest\x1a\x19.proplyd.v1.PurgeResponse\x12<\n" +
	"\x05Stats\x12\x18.proplyd.v1.StatsRequest\x1a\x19.proplyd.v1.StatsResponseB1Z/github.com/c12s/proplyd/api/proplydpb;proplydpbb\x06proto3"

var (
	file_proplyd_v1_cache_proto_rawDescOnce sync.Once
	file_proplyd_v1_cache_proto_rawDescData []byte
)

func file_proplyd_v1_cache_proto_rawDescGZIP() []byte {
	file_proplyd_v1_cache_proto_rawDescOnce.Do(func() {
		file_proplyd_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proplyd_v1_cache_proto_rawDesc), len(file_proplyd_v1_cache_proto_rawDesc)))
	})
	return file_proplyd_v1_cache_proto_rawDescData
}

var file_proplyd_v1_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proplyd_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proplyd_v1_cache_proto_goTypes = []any{
	(ReadStrategy)(0),                 // 0: proplyd.v1.ReadStrategy
	(WriteStrategy)(0),                // 1: proplyd.v1.WriteStrategy
	(EvictionPolicy)(0),               // 2: proplyd.v1.EvictionPolicy
	(SyncMode)(0),                     // 3: proplyd.v1.SyncMode
	(Outcome)(0),                      // 4: proplyd.v1.Outcome
	(*WriteBehindConfig)(nil),         // 5: proplyd.v1.WriteBehindConfig
	(*NamespaceConfig)(nil),           // 6: proplyd.v1.NamespaceConfig
	(*RegisterNamespaceRequest)(nil),  // 7: proplyd.v1.RegisterNamespaceRequest
	(*RegisterNamespaceResponse)(nil), // 8: proplyd.v1.RegisterNamespaceResponse
	(*GetRequest)(nil),                // 9: proplyd.v1.GetRequest
	(*GetResponse)(nil),               // 10: proplyd.v1.GetResponse
	(*SetRequest)(nil),                // 11: proplyd.v1.SetRequest
	(*SetResponse)(nil),               // 12: proplyd.v1.SetResponse
	(*DeleteRequest)(nil),             // 13: proplyd.v1.DeleteRequest
	(*DeleteResponse)(nil),            // 14: proplyd.v1.DeleteResponse
	(*FillRequest)(nil),               // 15: proplyd.v1.FillRequest
	(*FillResponse)(nil),              // 16: proplyd.v1.FillResponse
	(*InvalidateRequest)(nil),         // 17: proplyd.v1.InvalidateRequest
	(*InvalidateResponse)(nil),        // 18: proplyd.v1.InvalidateResponse
	(*PurgeRequest)(nil),              // 19: proplyd.v1.PurgeRequest
	(*PurgeResponse)(nil),             // 20: proplyd.v1.PurgeResponse
	(*StatsRequest)(nil),              // 21: proplyd.v1.StatsRequest
	(*StatsResponse)(nil),             // 22: proplyd.v1.StatsResponse
	(*durationpb.Duration)(nil),       // 23: google.protobuf.Duration
}
var file_proplyd_v1_cache_proto_depIdxs = []int32{
	23, // 0: proplyd.v1.WriteBehindConfig.flush_interval:type_name -> google.protobuf.Duration
	0,  // 1: proplyd.v1.NamespaceConfig.read_strategy:type_name -> proplyd.v1.ReadStrategy
	1,  // 2: proplyd.v1.NamespaceConfig.write_strategy:type_name -> proplyd.v1.WriteStrategy
	2,  // 3: proplyd.v1.NamespaceConfig.eviction_policy:type_name -> proplyd.v1.EvictionPolicy
	23, // 4: proplyd.v1.NamespaceConfig.ttl:type_name -> google.protobuf.Duration
	23, // 5: proplyd.v1.NamespaceConfig.refresh_after:type_name -> google.protobuf.Duration
	5,  // 6: proplyd.v1.NamespaceConfig.write_behind:type_name -> proplyd.v1.WriteBehindConfig
	3,  // 7: proplyd.v1.NamespaceConfig.sync_mode:type_name -> proplyd.v1.SyncMode
	6,  // 8: proplyd.v1.RegisterNamespaceRequest.config:type_name -> proplyd.v1.NamespaceConfig
	6,  // 9: proplyd.v1.RegisterNamespaceResponse.config:type_name -> proplyd.v1.NamespaceConfig
	4,  // 10: proplyd.v1.GetResponse.outcome:type_name -> proplyd.v1.Outcome
	23, // 11: proplyd.v1.SetRequest.ttl:type_name -> google.protobuf.Duration
	23, // 12: proplyd.v1.FillRequest.ttl:type_name -> google.protobuf.Duration
	7,  // 13: proplyd.v1.CacheService.RegisterNamespace:input_type -> proplyd.v1.RegisterNamespaceRequest
	9,  // 14: proplyd.v1.CacheService.Get:input_type -> proplyd.v1.GetRequest
	11, // 15: proplyd.v1.CacheService.Set:input_type -> proplyd.v1.SetRequest
	13, // 16: proplyd.v1.CacheService.Delete:input_type -> proplyd.v1.DeleteRequest
	15, // 17: proplyd.v1.CacheService.Fill:input_type -> proplyd.v1.FillRequest
	17, // 18: proplyd.v1.CacheService.Invalidate:input_type -> proplyd.v1.InvalidateRequest
	19, // 19: proplyd.v1.CacheService.Purge:input_type -> proplyd.v1.PurgeRequest
	21, // 20: proplyd.v1.CacheService.Stats:input_type -> proplyd.v1.StatsRequest
	8,  // 21: proplyd.v1.CacheService.RegisterNamespace:output_type -> proplyd.v1.RegisterNamespaceResponse
	10, // 22: proplyd.v1.CacheService.Get:output_type -> proplyd.v1.GetResponse
	12, // 23: proplyd.v1.CacheService.Set:output_type -> proplyd.v1.SetResponse
	14, // 24: proplyd.v1.CacheService.Delete:output_type -> proplyd.v1.DeleteResponse
	16, // 25: proplyd.v1.CacheService.Fill:output_type -> proplyd.v1.FillResponse
	18, // 26: proplyd.v1.CacheService.Invalidate:output_type -> proplyd.v1.InvalidateResponse
	20, // 27: proplyd.v1.CacheService.Purge:output_type -> proplyd.v1.PurgeResponse
	22, // 28: proplyd.v1.CacheService.Stats:output_type -> proplyd.v1.StatsResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proplyd_v1_cache_proto_init() }
func file_proplyd_v1_cache_proto_init() {
	if File_proplyd_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proplyd_v1_cache_proto_rawDesc), len(file_proplyd_v1_cache_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proplyd_v1_cache_proto_goTypes,
		DependencyIndexes: file_proplyd_v1_cache_proto_depIdxs,
		EnumInfos:         file_proplyd_v1_cache_proto_enumTypes,
		MessageInfos:      file_proplyd_v1_cache_proto_msgTypes,
	}.Build()
	File_proplyd_v1_cache_proto = out.File
	file_proplyd_v1_cache_proto_goTypes = nil
	file_proplyd_v1_cache_proto_depIdxs = nil
}
